### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by RandiakM** [theindianappguy/quizmakerapp#3]
The relevant error-causing widget was: 
  MyApp file:///E:/Flutter/quizmakerapp/lib/main.dart:9:10
When the exception was thrown, this was the stack: 
#0      _MyAppState.build (package:quizapp2/main.dart:44:13)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 575 libraries in 1,679ms.

could you please tell me how to fix this error?

**Comment by RandiakM** [comment]
getLoggedInState() async { 
    await Constants.getUerLoggedInSharedPreference().then((value) { 
      setState(() { 
        isUserLoggedIn = value ?? false;      
 });     
});  
 }
